<a href="https://colab.research.google.com/github/harsha361/zerotogans/blob/main/Copy_of_zero_to_gans.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import torchvision
import torch.nn as nn
import numpy as np
import torchvision.transforms as transforms


In [ ]:
x=torch.tensor(1.,requires_grad=True)
w=torch.tensor(2.,requires_grad=True)
b=torch.tensor(3.,requires_grad=True)

#building a computational graph
y=w*x+b
#compute gradients
y.backward()
#printing the gradients
print(x.grad)
print(w.grad)
print(b.grad)
x



tensor(2.)
tensor(1.)
tensor(1.)


tensor(1., requires_grad=True)

In [ ]:
#baisc auto grad example2
x=torch.randn(10,3)
y=torch.randn(10,2)
x,y

(tensor([[ 0.0205,  0.4011,  0.5630],
         [ 0.1499, -1.2534,  1.0989],
         [-0.5205,  1.8963, -0.5255],
         [-0.4348, -0.4124, -0.1040],
         [ 0.5007, -0.7695,  1.0679],
         [ 0.8344,  1.6033, -0.6566],
         [ 0.2344,  0.6499, -0.5887],
         [ 0.7655,  1.4887,  0.1893],
         [ 0.5373, -0.8724,  1.2098],
         [ 0.2101,  0.2396,  1.2717]]),
 tensor([[-0.3567,  1.3472],
         [ 1.1036, -0.6676],
         [-0.3192,  0.1493],
         [ 0.6985, -0.2528],
         [ 2.4350,  0.0450],
         [ 0.1231, -0.1341],
         [ 0.2297,  0.9698],
         [-0.9799,  1.8308],
         [ 0.2835,  0.2586],
         [ 1.2889, -0.9762]]))

In [ ]:
#building a fully connected linear layer
linear=nn.Linear(3,2)
print('w:',linear.weight)
print('b:',linear.bias)

w: Parameter containing:
tensor([[-0.4843,  0.5004, -0.5714],
        [ 0.4913,  0.0135, -0.0980]], requires_grad=True)
b: Parameter containing:
tensor([-0.3526, -0.2912], requires_grad=True)


In [ ]:
#lossfunction and optimizer
criterion=nn.MSELoss()
optimizer=torch.optim.SGD(linear.parameters(),lr=0.01)
#forward pass
pred=linear(x)
#compute loss
loss=criterion(pred,y)
print('loss:',loss.item())
#backward pass
loss.backward()

#printing the gradients
print('dl/dw:',linear.weight.grad)
print('dl/db:',linear.bias.grad)
#optimizer step
optimizer.step()

#printing the loss after 1 step gradient descent
pred=linear(x)
loss=criterion(pred,y)
print('loss after 1 step optimization:',loss.item())




loss: 1.7605899572372437
dl/dw: tensor([[ 0.2693, -0.0934, -2.0545],
        [-0.0363,  0.5590,  0.2183]])
dl/db: tensor([ 1.1618, -0.5611])
loss after 1 step optimization: 1.698185920715332


In [ ]:
linear=nn.Linear(3,2)
linear.weight

Parameter containing:
tensor([[-0.0754,  0.1555, -0.2577],
        [ 0.2163, -0.0331,  0.3289]], requires_grad=True)

In [ ]:
#loading data from numpy
x=np.array([[1,2],[3,4]])
y=torch.from_numpy(x)
z=y.numpy()

In [ ]:
#creating an input pipeline
train_dataset=torchvision.datasets.CIFAR10(root="../../data/",train=True,
                                           transform=transforms.ToTensor(),
                                           download=True)
image,label=train_dataset[0]
print(image.size())
print(label)



Files already downloaded and verified
torch.Size([3, 32, 32])
6


In [ ]:
#prpearing a dataloader(provides queues and threads)
train_loader=torch.utils.data.DataLoader(dataset=train_dataset,batch_size=64,
                                         shuffle=True)